image: node:14.16.1 # CHANGE THE VERSION IF YOU NEED 
pipelines:
  default:
    - step:
        name: Deploy VUE to S3
        deployment: Production
        script:
          - cd src
          - rm -rf node_modules
          - rm -rf dist
          - npm install 
          - npm run build 
          - cd ..
          - pipe: atlassian/aws-s3-deploy:0.4.4
            variables:
              AWS_ACCESS_KEY_ID: '$AWS_ACCESS_KEY_ID'
              AWS_SECRET_ACCESS_KEY: '$AWS_SECRET_ACCESS_KEY'
              AWS_DEFAULT_REGION: '$AWS_DEFAULT_REGION'
              S3_BUCKET: '$S3_BUCKET'
              LOCAL_PATH: '$LOCAL_PATH'
              ACL: '$ACL'
              CACHE_CONTROL: 'no-cache'
              # CONTENT_ENCODING: '<string>' # Optional.
              # STORAGE_CLASS: '<string>' # Optional.
              # CACHE_CONTROL: '<string>' # Optional.
              # EXPIRES: '<timestamp>' # Optional.
              # DELETE_FLAG: '<boolean>' # Optional.
              # EXTRA_ARGS: '<string>' # Optional.
              DEBUG: '$DEBUG'
